// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appswitchermodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the AppSwitcherModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_CustomAuthenticationBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AppSwitcherModule.DS_CustomAuthentication");
		return builder;
	}

	public static java.lang.String dS_CustomAuthentication(IContext context)
	{
		Object result = dS_CustomAuthenticationBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder parseAuthorizationBuilder(
		java.lang.String _customAuthToken
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AppSwitcherModule.ParseAuthorization");
		builder = builder.withParam("customAuthToken", _customAuthToken);
		return builder;
	}

	public static appswitchermodule.proxies.CustomToken parseAuthorization(
		IContext context,
		java.lang.String _customAuthToken
	)
	{
		Object result = parseAuthorizationBuilder(
				_customAuthToken
			)
			.execute(context);
		return result == null ? null : appswitchermodule.proxies.CustomToken.initialize(context, (IMendixObject) result);
	}
}
