// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tasktracker.proxies;

public class FileUpload extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TaskTracker.FileUpload";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		FileUpload_Task("TaskTracker.FileUpload_Task"),
		FileUpload_MendixSSOUser_Account("TaskTracker.FileUpload_MendixSSOUser_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FileUpload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FileUpload(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fileUploadMendixObject)
	{
		super(context, fileUploadMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, fileUploadMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static tasktracker.proxies.FileUpload initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tasktracker.proxies.FileUpload(context, mendixObject);
	}

	public static tasktracker.proxies.FileUpload load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tasktracker.proxies.FileUpload.initialize(context, mendixObject);
	}

	public static java.util.List<tasktracker.proxies.FileUpload> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> tasktracker.proxies.FileUpload.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FileUpload_Task
	 */
	public final tasktracker.proxies.Task getFileUpload_Task() throws com.mendix.core.CoreException
	{
		return getFileUpload_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of FileUpload_Task
	 * @throws com.mendix.core.CoreException
	 */
	public final tasktracker.proxies.Task getFileUpload_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		tasktracker.proxies.Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FileUpload_Task.toString());
		if (identifier != null) {
			result = tasktracker.proxies.Task.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FileUpload_Task
	 * @param fileupload_task
	 */
	public final void setFileUpload_Task(tasktracker.proxies.Task fileupload_task)
	{
		setFileUpload_Task(getContext(), fileupload_task);
	}

	/**
	 * Set value of FileUpload_Task
	 * @param context
	 * @param fileupload_task
	 */
	public final void setFileUpload_Task(com.mendix.systemwideinterfaces.core.IContext context, tasktracker.proxies.Task fileupload_task)
	{
		if (fileupload_task == null) {
			getMendixObject().setValue(context, MemberNames.FileUpload_Task.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FileUpload_Task.toString(), fileupload_task.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FileUpload_MendixSSOUser_Account
	 */
	public final mendixsso.proxies.MendixSSOUser getFileUpload_MendixSSOUser_Account() throws com.mendix.core.CoreException
	{
		return getFileUpload_MendixSSOUser_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of FileUpload_MendixSSOUser_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final mendixsso.proxies.MendixSSOUser getFileUpload_MendixSSOUser_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mendixsso.proxies.MendixSSOUser result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FileUpload_MendixSSOUser_Account.toString());
		if (identifier != null) {
			result = mendixsso.proxies.MendixSSOUser.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FileUpload_MendixSSOUser_Account
	 * @param fileupload_mendixssouser_account
	 */
	public final void setFileUpload_MendixSSOUser_Account(mendixsso.proxies.MendixSSOUser fileupload_mendixssouser_account)
	{
		setFileUpload_MendixSSOUser_Account(getContext(), fileupload_mendixssouser_account);
	}

	/**
	 * Set value of FileUpload_MendixSSOUser_Account
	 * @param context
	 * @param fileupload_mendixssouser_account
	 */
	public final void setFileUpload_MendixSSOUser_Account(com.mendix.systemwideinterfaces.core.IContext context, mendixsso.proxies.MendixSSOUser fileupload_mendixssouser_account)
	{
		if (fileupload_mendixssouser_account == null) {
			getMendixObject().setValue(context, MemberNames.FileUpload_MendixSSOUser_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FileUpload_MendixSSOUser_Account.toString(), fileupload_mendixssouser_account.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tasktracker.proxies.FileUpload that = (tasktracker.proxies.FileUpload) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
