// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tasktracker.proxies;

public class PageHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pageHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TaskTracker.PageHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TeamProgress("TeamProgress"),
		AssignedTasks("AssignedTasks");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PageHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PageHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pageHelperMendixObject)
	{
		if (pageHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, pageHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.pageHelperMendixObject = pageHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static tasktracker.proxies.PageHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tasktracker.proxies.PageHelper(context, mendixObject);
	}

	public static tasktracker.proxies.PageHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tasktracker.proxies.PageHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of TeamProgress
	 */
	public final java.math.BigDecimal getTeamProgress()
	{
		return getTeamProgress(getContext());
	}

	/**
	 * @param context
	 * @return value of TeamProgress
	 */
	public final java.math.BigDecimal getTeamProgress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TeamProgress.toString());
	}

	/**
	 * Set value of TeamProgress
	 * @param teamprogress
	 */
	public final void setTeamProgress(java.math.BigDecimal teamprogress)
	{
		setTeamProgress(getContext(), teamprogress);
	}

	/**
	 * Set value of TeamProgress
	 * @param context
	 * @param teamprogress
	 */
	public final void setTeamProgress(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal teamprogress)
	{
		getMendixObject().setValue(context, MemberNames.TeamProgress.toString(), teamprogress);
	}

	/**
	 * @return value of AssignedTasks
	 */
	public final java.lang.Integer getAssignedTasks()
	{
		return getAssignedTasks(getContext());
	}

	/**
	 * @param context
	 * @return value of AssignedTasks
	 */
	public final java.lang.Integer getAssignedTasks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AssignedTasks.toString());
	}

	/**
	 * Set value of AssignedTasks
	 * @param assignedtasks
	 */
	public final void setAssignedTasks(java.lang.Integer assignedtasks)
	{
		setAssignedTasks(getContext(), assignedtasks);
	}

	/**
	 * Set value of AssignedTasks
	 * @param context
	 * @param assignedtasks
	 */
	public final void setAssignedTasks(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer assignedtasks)
	{
		getMendixObject().setValue(context, MemberNames.AssignedTasks.toString(), assignedtasks);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pageHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tasktracker.proxies.PageHelper that = (tasktracker.proxies.PageHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
