// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tasktracker.proxies;

public class Task implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TaskTracker.Task";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		DueDate("DueDate"),
		Priority("Priority"),
		Status("Status"),
		SLADashboardStatus("SLADashboardStatus"),
		CompletionDate("CompletionDate"),
		Task_Department("TaskTracker.Task_Department"),
		Task_MendixSSOUser_Assignee("TaskTracker.Task_MendixSSOUser_Assignee");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Task(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Task(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskMendixObject)
	{
		if (taskMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, taskMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.taskMendixObject = taskMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static tasktracker.proxies.Task initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tasktracker.proxies.Task(context, mendixObject);
	}

	public static tasktracker.proxies.Task load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tasktracker.proxies.Task.initialize(context, mendixObject);
	}

	public static java.util.List<tasktracker.proxies.Task> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> tasktracker.proxies.Task.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate()
	{
		return getDueDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DueDate.toString());
	}

	/**
	 * Set value of DueDate
	 * @param duedate
	 */
	public final void setDueDate(java.util.Date duedate)
	{
		setDueDate(getContext(), duedate);
	}

	/**
	 * Set value of DueDate
	 * @param context
	 * @param duedate
	 */
	public final void setDueDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date duedate)
	{
		getMendixObject().setValue(context, MemberNames.DueDate.toString(), duedate);
	}

	/**
	 * Get value of Priority
	 * @param priority
	 */
	public final tasktracker.proxies.ENUM_Priority getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final tasktracker.proxies.ENUM_Priority getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Priority.toString());
		if (obj == null) {
			return null;
		}
		return tasktracker.proxies.ENUM_Priority.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(tasktracker.proxies.ENUM_Priority priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, tasktracker.proxies.ENUM_Priority priority)
	{
		if (priority != null) {
			getMendixObject().setValue(context, MemberNames.Priority.toString(), priority.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Priority.toString(), null);
		}
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final tasktracker.proxies.ENUM_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final tasktracker.proxies.ENUM_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return tasktracker.proxies.ENUM_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(tasktracker.proxies.ENUM_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, tasktracker.proxies.ENUM_Status status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * Get value of SLADashboardStatus
	 * @param sladashboardstatus
	 */
	public final tasktracker.proxies.ENUM_SLADashboardStatus getSLADashboardStatus()
	{
		return getSLADashboardStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of SLADashboardStatus
	 */
	public final tasktracker.proxies.ENUM_SLADashboardStatus getSLADashboardStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SLADashboardStatus.toString());
		if (obj == null) {
			return null;
		}
		return tasktracker.proxies.ENUM_SLADashboardStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SLADashboardStatus
	 * @param sladashboardstatus
	 */
	public final void setSLADashboardStatus(tasktracker.proxies.ENUM_SLADashboardStatus sladashboardstatus)
	{
		setSLADashboardStatus(getContext(), sladashboardstatus);
	}

	/**
	 * Set value of SLADashboardStatus
	 * @param context
	 * @param sladashboardstatus
	 */
	public final void setSLADashboardStatus(com.mendix.systemwideinterfaces.core.IContext context, tasktracker.proxies.ENUM_SLADashboardStatus sladashboardstatus)
	{
		if (sladashboardstatus != null) {
			getMendixObject().setValue(context, MemberNames.SLADashboardStatus.toString(), sladashboardstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SLADashboardStatus.toString(), null);
		}
	}

	/**
	 * @return value of CompletionDate
	 */
	public final java.util.Date getCompletionDate()
	{
		return getCompletionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletionDate
	 */
	public final java.util.Date getCompletionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CompletionDate.toString());
	}

	/**
	 * Set value of CompletionDate
	 * @param completiondate
	 */
	public final void setCompletionDate(java.util.Date completiondate)
	{
		setCompletionDate(getContext(), completiondate);
	}

	/**
	 * Set value of CompletionDate
	 * @param context
	 * @param completiondate
	 */
	public final void setCompletionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date completiondate)
	{
		getMendixObject().setValue(context, MemberNames.CompletionDate.toString(), completiondate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_Department
	 */
	public final tasktracker.proxies.Department getTask_Department() throws com.mendix.core.CoreException
	{
		return getTask_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final tasktracker.proxies.Department getTask_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		tasktracker.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_Department.toString());
		if (identifier != null) {
			result = tasktracker.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_Department
	 * @param task_department
	 */
	public final void setTask_Department(tasktracker.proxies.Department task_department)
	{
		setTask_Department(getContext(), task_department);
	}

	/**
	 * Set value of Task_Department
	 * @param context
	 * @param task_department
	 */
	public final void setTask_Department(com.mendix.systemwideinterfaces.core.IContext context, tasktracker.proxies.Department task_department)
	{
		if (task_department == null) {
			getMendixObject().setValue(context, MemberNames.Task_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_Department.toString(), task_department.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_MendixSSOUser_Assignee
	 */
	public final mendixsso.proxies.MendixSSOUser getTask_MendixSSOUser_Assignee() throws com.mendix.core.CoreException
	{
		return getTask_MendixSSOUser_Assignee(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_MendixSSOUser_Assignee
	 * @throws com.mendix.core.CoreException
	 */
	public final mendixsso.proxies.MendixSSOUser getTask_MendixSSOUser_Assignee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mendixsso.proxies.MendixSSOUser result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_MendixSSOUser_Assignee.toString());
		if (identifier != null) {
			result = mendixsso.proxies.MendixSSOUser.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_MendixSSOUser_Assignee
	 * @param task_mendixssouser_assignee
	 */
	public final void setTask_MendixSSOUser_Assignee(mendixsso.proxies.MendixSSOUser task_mendixssouser_assignee)
	{
		setTask_MendixSSOUser_Assignee(getContext(), task_mendixssouser_assignee);
	}

	/**
	 * Set value of Task_MendixSSOUser_Assignee
	 * @param context
	 * @param task_mendixssouser_assignee
	 */
	public final void setTask_MendixSSOUser_Assignee(com.mendix.systemwideinterfaces.core.IContext context, mendixsso.proxies.MendixSSOUser task_mendixssouser_assignee)
	{
		if (task_mendixssouser_assignee == null) {
			getMendixObject().setValue(context, MemberNames.Task_MendixSSOUser_Assignee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_MendixSSOUser_Assignee.toString(), task_mendixssouser_assignee.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tasktracker.proxies.Task that = (tasktracker.proxies.Task) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
