// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mendixsso.proxies;

public class AdditionalScopes implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject additionalScopesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MendixSSO.AdditionalScopes";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AdditionalScopes("AdditionalScopes");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AdditionalScopes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AdditionalScopes(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject additionalScopesMendixObject)
	{
		if (additionalScopesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, additionalScopesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.additionalScopesMendixObject = additionalScopesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mendixsso.proxies.AdditionalScopes initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mendixsso.proxies.AdditionalScopes(context, mendixObject);
	}

	public static mendixsso.proxies.AdditionalScopes load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mendixsso.proxies.AdditionalScopes.initialize(context, mendixObject);
	}

	/**
	 * @return value of AdditionalScopes
	 */
	public final java.lang.String getAdditionalScopes()
	{
		return getAdditionalScopes(getContext());
	}

	/**
	 * @param context
	 * @return value of AdditionalScopes
	 */
	public final java.lang.String getAdditionalScopes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AdditionalScopes.toString());
	}

	/**
	 * Set value of AdditionalScopes
	 * @param additionalscopes
	 */
	public final void setAdditionalScopes(java.lang.String additionalscopes)
	{
		setAdditionalScopes(getContext(), additionalscopes);
	}

	/**
	 * Set value of AdditionalScopes
	 * @param context
	 * @param additionalscopes
	 */
	public final void setAdditionalScopes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String additionalscopes)
	{
		getMendixObject().setValue(context, MemberNames.AdditionalScopes.toString(), additionalscopes);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return additionalScopesMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mendixsso.proxies.AdditionalScopes that = (mendixsso.proxies.AdditionalScopes) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
